# fruits = ["apple", "banana", "cherry"]
# for x in fruits:
#   print(x) 


# for x in "banana":
# #   print(x)

# fruits = ["apple", "banana", "cherry"]
# for x in fruits:
#   print(x)
# #   if x == "banana":
# #    
# 
#  break
# for x in range(6):
#   print(x)

#   for x in range(2, 6):
#   print(x)

adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
  for y in fruits:
    print(x, y)


    # pares = 0

# for cont in range(5):

#     num = int(input("Digite um número: "))
#     if num % 2 == 0:
#         pares += 1

# print(f"Quantidade de números pares digitados: {pares}")